/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author Erwin
 */
public class aplicacion_completa extends javax.swing.JFrame {
    QueueArrayGeneric<Date> fechas=new QueueArrayGeneric<Date>();
    /**
     * Creates new form aplicacion_completa
     */
    public aplicacion_completa() {
        initComponents();
        this.setLocationRelativeTo(null);
        Datos.setVisible(false);
        Valores.setVisible(false);
    }
    public  double redondearDecimales(double valorInicial, int numeroDecimales) {
        double parteEntera, resultado;
        resultado = valorInicial;
        parteEntera = Math.floor(resultado);
        resultado=(resultado-parteEntera)*Math.pow(10, numeroDecimales);
        resultado=Math.round(resultado);
        resultado=(resultado/Math.pow(10, numeroDecimales))+parteEntera;
        return resultado;
    }
     public double calcular_valor(int cantidad, int metro_cubico_arbol ){
    double valor=0;    
    for (int i=0; i<cantidad; i++){
      int ano_arbol=obtenerAnios(fechas.dequeue());      
      double metro_cubico=(3.1415*(Math.pow((ano_arbol/0.2)/2,2))*(ano_arbol*1.5))/1000000; 
      double metro_redonde=redondearDecimales(metro_cubico,2);
      double valor_arbol=metro_redonde*metro_cubico_arbol;
      valor=valor+valor_arbol;
    }
    return valor;              

  }
      public  int obtenerAnios(Date firts) {
       //Date first= fecha_inicial.getDatoFecha();
        Date last= Fecha_fin.getDatoFecha();
        Calendar a = getCalendar(firts);
        Calendar b = getCalendar(last);
        int diff = b.get(Calendar.YEAR) - a.get(Calendar.YEAR);        
        
        if (a.get(Calendar.MONTH) > b.get(Calendar.MONTH) ||
            (a.get(Calendar.MONTH) == b.get(Calendar.MONTH) &&   
            a.get(Calendar.DATE) > b.get(Calendar.DATE))) {
            diff--;
        }
        return diff;
    }
       public static Calendar getCalendar(Date date) {
        Calendar cal = Calendar.getInstance(Locale.US);
        cal.setTime(date);
        return cal;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Valores = new javax.swing.JPanel();
        t_fecha_in = new javax.swing.JLabel();
        t_fecha_fin = new javax.swing.JLabel();
        t_Cantidad = new javax.swing.JLabel();
        t_Valor_madera = new javax.swing.JLabel();
        t_Consultar = new javax.swing.JLabel();
        Fecha_ini = new rojeru_san.componentes.RSDateChooser();
        Fecha_fin = new rojeru_san.componentes.RSDateChooser();
        Cantidad = new javax.swing.JTextField();
        Valor_mad = new javax.swing.JTextField();
        Consultar_valor = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        SAlir2 = new javax.swing.JButton();
        Regresa1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        Mostrar_res = new javax.swing.JOptionPane();
        presentacion = new javax.swing.JPanel();
        text_ingresar_datos = new javax.swing.JLabel();
        T_consultar_valores = new javax.swing.JLabel();
        B_ingres_datos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Regresa = new javax.swing.JButton();
        SAlir1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        Datos = new javax.swing.JPanel();
        t_ingresar_fecha = new javax.swing.JLabel();
        t_ingresar_cantidad = new javax.swing.JLabel();
        Fecha = new rojeru_san.componentes.RSDateChooser();
        Cant_arb = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        logo2 = new javax.swing.JLabel();
        Regresar1 = new javax.swing.JButton();
        SAlir = new javax.swing.JButton();
        Fondo3 = new javax.swing.JLabel();
        mensaje_resultado = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Valores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_fecha_in.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        t_fecha_in.setText("Ingrese Fecha Inincial");
        Valores.add(t_fecha_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        t_fecha_fin.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        t_fecha_fin.setText("Ingrese Fecha Final");
        Valores.add(t_fecha_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        t_Cantidad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        t_Cantidad.setText("Ingrese Cantidad a Conocer");
        Valores.add(t_Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        t_Valor_madera.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        t_Valor_madera.setText("Ingrese Valor metro cubico Madera");
        Valores.add(t_Valor_madera, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        t_Consultar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        t_Consultar.setText("Consultar Valor");
        Valores.add(t_Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));
        Valores.add(Fecha_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));
        Valores.add(Fecha_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));
        Valores.add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 90, 30));
        Valores.add(Valor_mad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 90, 30));

        Consultar_valor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagescon_valor.png"))); // NOI18N
        Consultar_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar_valorActionPerformed(evt);
            }
        });
        Valores.add(Consultar_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 160, 150));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo apli3.png"))); // NOI18N
        Valores.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        SAlir2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SAlir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir2.png"))); // NOI18N
        SAlir2.setText("Salir");
        SAlir2.setContentAreaFilled(false);
        SAlir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAlir2ActionPerformed(evt);
            }
        });
        Valores.add(SAlir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        Regresa1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Regresa1.setForeground(new java.awt.Color(255, 255, 255));
        Regresa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar2.png"))); // NOI18N
        Regresa1.setText("Regresar");
        Regresa1.setContentAreaFilled(false);
        Regresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresa1ActionPerformed(evt);
            }
        });
        Valores.add(Regresa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.jpg"))); // NOI18N
        Valores.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));
        Valores.add(Mostrar_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 330, -1, 10));

        getContentPane().add(Valores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        presentacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_ingresar_datos.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        text_ingresar_datos.setForeground(new java.awt.Color(255, 255, 255));
        text_ingresar_datos.setText("Ingresar Datos");
        presentacion.add(text_ingresar_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        T_consultar_valores.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        T_consultar_valores.setForeground(new java.awt.Color(255, 255, 255));
        T_consultar_valores.setText("Consultar Valores");
        presentacion.add(T_consultar_valores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        B_ingres_datos.setBackground(new java.awt.Color(204, 204, 204));
        B_ingres_datos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datos_per1.png"))); // NOI18N
        B_ingres_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ingres_datosActionPerformed(evt);
            }
        });
        presentacion.add(B_ingres_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 150, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/valor_pes.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        presentacion.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 150, 70));

        Titulo.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("VALOR PLANTACION");
        presentacion.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo apli3.png"))); // NOI18N
        presentacion.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        Regresa.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Regresa.setForeground(new java.awt.Color(255, 255, 255));
        Regresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar2.png"))); // NOI18N
        Regresa.setText("Regresar");
        Regresa.setContentAreaFilled(false);
        presentacion.add(Regresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, -1, -1));

        SAlir1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SAlir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir2.png"))); // NOI18N
        SAlir1.setText("Salir");
        SAlir1.setContentAreaFilled(false);
        SAlir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAlir1ActionPerformed(evt);
            }
        });
        presentacion.add(SAlir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/green.jpg"))); // NOI18N
        presentacion.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 910, 590));

        getContentPane().add(presentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 850, 480));

        Datos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_ingresar_fecha.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        t_ingresar_fecha.setForeground(new java.awt.Color(255, 255, 255));
        t_ingresar_fecha.setText("Ingresar Fecha");
        Datos.add(t_ingresar_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        t_ingresar_cantidad.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        t_ingresar_cantidad.setForeground(new java.awt.Color(255, 255, 255));
        t_ingresar_cantidad.setText("Ingresar Cantidad");
        Datos.add(t_ingresar_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));
        Datos.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));
        Datos.add(Cant_arb, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 110, 40));

        jButton2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton2.setText("Ingresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Datos.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 100, 40));

        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo apli3.png"))); // NOI18N
        Datos.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        Regresar1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Regresar1.setForeground(new java.awt.Color(255, 255, 255));
        Regresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar2.png"))); // NOI18N
        Regresar1.setText("Regresar");
        Regresar1.setContentAreaFilled(false);
        Regresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar1ActionPerformed(evt);
            }
        });
        Datos.add(Regresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, -1));

        SAlir.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SAlir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir2.png"))); // NOI18N
        SAlir.setText("Salir");
        SAlir.setContentAreaFilled(false);
        SAlir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAlirActionPerformed(evt);
            }
        });
        Datos.add(SAlir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        Fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datos11.jpg"))); // NOI18N
        Datos.add(Fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        Datos.add(mensaje_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 10, 20));

        getContentPane().add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Regresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar1ActionPerformed
        presentacion.setVisible(true);
        Datos.setVisible(false);
    }//GEN-LAST:event_Regresar1ActionPerformed

    private void B_ingres_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ingres_datosActionPerformed
        Datos.setVisible(true);
        presentacion.setVisible(false);
    }//GEN-LAST:event_B_ingres_datosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Date a = Fecha.getDatoFecha();
        int b= Integer.parseInt(Cant_arb.getText());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        //Calendar cal = getCalendar(a);
        for(int i=0; i<b; i++){
           fechas.enqueue(a);           
        }        
        mensaje_resultado.showMessageDialog(null,b+" Datos Ingresados con la fecha "+ sdf.format(a));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SAlirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAlirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SAlirActionPerformed

    private void Consultar_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar_valorActionPerformed
        int cant=Integer.parseInt(Cantidad.getText());
        int val_mad=Integer.parseInt(Valor_mad.getText());
        Mostrar_res.showMessageDialog(null,"el valor para los datos seleccionados es "+ calcular_valor(cant,val_mad));
    }//GEN-LAST:event_Consultar_valorActionPerformed

    private void SAlir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAlir2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SAlir2ActionPerformed

    private void Regresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresa1ActionPerformed
        Valores.setVisible(false);
        presentacion.setVisible(true);
    }//GEN-LAST:event_Regresa1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        presentacion.setVisible(false);
        Valores.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SAlir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAlir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SAlir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplicacion_completa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplicacion_completa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplicacion_completa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplicacion_completa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplicacion_completa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_ingres_datos;
    private javax.swing.JTextField Cant_arb;
    private javax.swing.JTextField Cantidad;
    private javax.swing.JButton Consultar_valor;
    private javax.swing.JPanel Datos;
    private rojeru_san.componentes.RSDateChooser Fecha;
    private rojeru_san.componentes.RSDateChooser Fecha_fin;
    private rojeru_san.componentes.RSDateChooser Fecha_ini;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo3;
    private javax.swing.JLabel Logo;
    private javax.swing.JOptionPane Mostrar_res;
    private javax.swing.JButton Regresa;
    private javax.swing.JButton Regresa1;
    private javax.swing.JButton Regresar1;
    private javax.swing.JButton SAlir;
    private javax.swing.JButton SAlir1;
    private javax.swing.JButton SAlir2;
    private javax.swing.JLabel T_consultar_valores;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField Valor_mad;
    private javax.swing.JPanel Valores;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo2;
    private javax.swing.JOptionPane mensaje_resultado;
    private javax.swing.JPanel presentacion;
    private javax.swing.JLabel t_Cantidad;
    private javax.swing.JLabel t_Consultar;
    private javax.swing.JLabel t_Valor_madera;
    private javax.swing.JLabel t_fecha_fin;
    private javax.swing.JLabel t_fecha_in;
    private javax.swing.JLabel t_ingresar_cantidad;
    private javax.swing.JLabel t_ingresar_fecha;
    private javax.swing.JLabel text_ingresar_datos;
    // End of variables declaration//GEN-END:variables
}
