/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author Erwin
 */
public class aplicacion_completa extends javax.swing.JFrame {
    QueueArrayGeneric<Date> fechas=new QueueArrayGeneric<Date>();
    /**
     * Creates new form aplicacion_completa
     */
    public aplicacion_completa() {
        initComponents();
        this.setLocationRelativeTo(null);
        Datos.setVisible(false);
        Valores.setVisible(false);
        Lanzar_aplix.setVisible(false);
        presentacion.setVisible(false);
        
    }
    public  double redondearDecimales(double valorInicial, int numeroDecimales) {
        double parteEntera, resultado;
        resultado = valorInicial;
        parteEntera = Math.floor(resultado);
        resultado=(resultado-parteEntera)*Math.pow(10, numeroDecimales);
        resultado=Math.round(resultado);
        resultado=(resultado/Math.pow(10, numeroDecimales))+parteEntera;
        return resultado;
    }
     public double calcular_valor(int cantidad, int metro_cubico_arbol ){
    double valor=0;    
    for (int i=0; i<cantidad; i++){
      int ano_arbol=obtenerAnios(fechas.dequeue());      
      double metro_cubico=(3.1415*(Math.pow((ano_arbol/0.2)/2,2))*(ano_arbol*1.5))/1000000; 
      double metro_redonde=redondearDecimales(metro_cubico,2);
      double valor_arbol=metro_redonde*metro_cubico_arbol;
      valor=valor+valor_arbol;
    }
    return valor;              

  }
      public  int obtenerAnios(Date firts) {
       //Date first= fecha_inicial.getDatoFecha();
        Date last= Fecha_fin.getDatoFecha();
        Calendar a = getCalendar(firts);
        Calendar b = getCalendar(last);
        int diff = b.get(Calendar.YEAR) - a.get(Calendar.YEAR);        
        
        if (a.get(Calendar.MONTH) > b.get(Calendar.MONTH) ||
            (a.get(Calendar.MONTH) == b.get(Calendar.MONTH) &&   
            a.get(Calendar.DATE) > b.get(Calendar.DATE))) {
            diff--;
        }
        return diff;
    }
       public static Calendar getCalendar(Date date) {
        Calendar cal = Calendar.getInstance(Locale.US);
        cal.setTime(date);
        return cal;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aaranque = new javax.swing.JPanel();
        contraseña = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        entrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fondo_inicial = new javax.swing.JLabel();
        Error_contra = new javax.swing.JOptionPane();
        Lanzar_aplix = new javax.swing.JPanel();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        imagen_1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imagen_2 = new javax.swing.JLabel();
        imgen_4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        fondo_lanza = new javax.swing.JLabel();
        presentacion = new javax.swing.JPanel();
        text_ingresar_datos = new javax.swing.JLabel();
        T_consultar_valores = new javax.swing.JLabel();
        B_ingres_datos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Regresa = new javax.swing.JButton();
        SAlir1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        Datos = new javax.swing.JPanel();
        t_ingresar_fecha = new javax.swing.JLabel();
        t_ingresar_cantidad = new javax.swing.JLabel();
        Fecha = new rojeru_san.componentes.RSDateChooser();
        Cant_arb = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        logo2 = new javax.swing.JLabel();
        Regresar1 = new javax.swing.JButton();
        SAlir = new javax.swing.JButton();
        Fondo3 = new javax.swing.JLabel();
        mensaje_resultado = new javax.swing.JOptionPane();
        Valores = new javax.swing.JPanel();
        t_fecha_in = new javax.swing.JLabel();
        t_fecha_fin = new javax.swing.JLabel();
        t_Cantidad = new javax.swing.JLabel();
        t_Valor_madera = new javax.swing.JLabel();
        t_Consultar = new javax.swing.JLabel();
        Fecha_ini = new rojeru_san.componentes.RSDateChooser();
        Fecha_fin = new rojeru_san.componentes.RSDateChooser();
        Cantidad = new javax.swing.JTextField();
        Valor_mad = new javax.swing.JTextField();
        Consultar_valor = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        SAlir2 = new javax.swing.JButton();
        Regresa1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        Mostrar_res = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aaranque.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contraseña.setBackground(new java.awt.Color(255, 255, 255));
        contraseña.setText("Contraseña");
        aaranque.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 190, 40));

        usuario.setBackground(new java.awt.Color(255, 255, 255));
        usuario.setText("Ususario");
        aaranque.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 190, 40));

        entrar.setBackground(new java.awt.Color(204, 204, 204));
        entrar.setForeground(new java.awt.Color(0, 0, 0));
        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        aaranque.add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 140, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usus4.png"))); // NOI18N
        aaranque.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        fondo_inicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo_ini2.jpg"))); // NOI18N
        aaranque.add(fondo_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));
        aaranque.add(Error_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        getContentPane().add(aaranque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        Lanzar_aplix.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1.jpg"))); // NOI18N
        boton1.setBorderPainted(false);
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        Lanzar_aplix.add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 70));

        boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton2.jpg"))); // NOI18N
        boton2.setBorderPainted(false);
        Lanzar_aplix.add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 140, 70));

        boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boyon3.jpg"))); // NOI18N
        boton3.setBorderPainted(false);
        Lanzar_aplix.add(boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 140, 70));

        boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton4.jpg"))); // NOI18N
        boton4.setBorderPainted(false);
        Lanzar_aplix.add(boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 150, 70));

        imagen_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1.jpg"))); // NOI18N
        Lanzar_aplix.add(imagen_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton2.jpg"))); // NOI18N
        Lanzar_aplix.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        imagen_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boyon3.jpg"))); // NOI18N
        Lanzar_aplix.add(imagen_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        imgen_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton4.jpg"))); // NOI18N
        Lanzar_aplix.add(imgen_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea1.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("En esta opcion podra agregar los datos de las diferentes plantacionescon sus fechas para posteriormente consultar sus valores");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea1);

        Lanzar_aplix.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 190, 90));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea2.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("En esta opcion podra agregar los datos de las diferentes plantacionescon sus fechas para posteriormente consultar sus valores");
        jTextArea2.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea2);

        Lanzar_aplix.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 190, 90));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea3.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("En esta opcion podra agregar los datos de las diferentes plantacionescon sus fechas para posteriormente consultar sus valores");
        jTextArea3.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextArea3);

        Lanzar_aplix.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 190, 90));

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea4.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea4.setColumns(20);
        jTextArea4.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("En esta opcion podra agregar los datos de las diferentes plantacionescon sus fechas para posteriormente consultar sus valores");
        jTextArea4.setWrapStyleWord(true);
        jScrollPane5.setViewportView(jTextArea4);

        Lanzar_aplix.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 190, 90));

        fondo_lanza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/intermedio proyecto.jpg"))); // NOI18N
        Lanzar_aplix.add(fondo_lanza, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(Lanzar_aplix, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        presentacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_ingresar_datos.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        text_ingresar_datos.setForeground(new java.awt.Color(0, 0, 0));
        text_ingresar_datos.setText("Ingresar Datos");
        presentacion.add(text_ingresar_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        T_consultar_valores.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        T_consultar_valores.setForeground(new java.awt.Color(0, 0, 0));
        T_consultar_valores.setText("Consultar Valores");
        presentacion.add(T_consultar_valores, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        B_ingres_datos.setBackground(new java.awt.Color(204, 204, 204));
        B_ingres_datos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datos_per1.png"))); // NOI18N
        B_ingres_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ingres_datosActionPerformed(evt);
            }
        });
        presentacion.add(B_ingres_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 150, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/valor_pes.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        presentacion.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 150, 70));

        Titulo.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("VALOR PLANTACION");
        presentacion.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        Logo.setForeground(new java.awt.Color(0, 0, 0));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo apli3negro2.png"))); // NOI18N
        presentacion.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        Regresa.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Regresa.setForeground(new java.awt.Color(0, 0, 0));
        Regresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresa_negro.png"))); // NOI18N
        Regresa.setText("Regresar");
        Regresa.setContentAreaFilled(false);
        Regresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresaActionPerformed(evt);
            }
        });
        presentacion.add(Regresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, -1, -1));

        SAlir1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SAlir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir2.png"))); // NOI18N
        SAlir1.setText("Salir");
        SAlir1.setContentAreaFilled(false);
        SAlir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAlir1ActionPerformed(evt);
            }
        });
        presentacion.add(SAlir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/todas_proy.jpg"))); // NOI18N
        presentacion.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(presentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 800, 600));

        Datos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_ingresar_fecha.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        t_ingresar_fecha.setForeground(new java.awt.Color(0, 0, 0));
        t_ingresar_fecha.setText("Ingresar Fecha");
        Datos.add(t_ingresar_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        t_ingresar_cantidad.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        t_ingresar_cantidad.setForeground(new java.awt.Color(0, 0, 0));
        t_ingresar_cantidad.setText("Ingresar Cantidad");
        Datos.add(t_ingresar_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));
        Datos.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));
        Datos.add(Cant_arb, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 110, 40));

        jButton2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Ingresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Datos.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 100, 40));

        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo apli3negro2.png"))); // NOI18N
        Datos.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        Regresar1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Regresar1.setForeground(new java.awt.Color(0, 0, 0));
        Regresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresa_negro.png"))); // NOI18N
        Regresar1.setText("Regresar");
        Regresar1.setContentAreaFilled(false);
        Regresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar1ActionPerformed(evt);
            }
        });
        Datos.add(Regresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, -1, -1));

        SAlir.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SAlir.setForeground(new java.awt.Color(0, 0, 0));
        SAlir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir2.png"))); // NOI18N
        SAlir.setText("Salir");
        SAlir.setContentAreaFilled(false);
        SAlir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAlirActionPerformed(evt);
            }
        });
        Datos.add(SAlir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        Fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/todas_proy.jpg"))); // NOI18N
        Datos.add(Fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        Datos.add(mensaje_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 10, 20));

        getContentPane().add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        Valores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_fecha_in.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        t_fecha_in.setForeground(new java.awt.Color(0, 0, 0));
        t_fecha_in.setText("Ingrese Fecha Inincial");
        Valores.add(t_fecha_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        t_fecha_fin.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        t_fecha_fin.setForeground(new java.awt.Color(0, 0, 0));
        t_fecha_fin.setText("Ingrese Fecha Final");
        Valores.add(t_fecha_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        t_Cantidad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        t_Cantidad.setForeground(new java.awt.Color(0, 0, 0));
        t_Cantidad.setText("Ingrese Cantidad a Conocer");
        Valores.add(t_Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        t_Valor_madera.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        t_Valor_madera.setForeground(new java.awt.Color(0, 0, 0));
        t_Valor_madera.setText("Ingrese Valor metro cubico Madera");
        Valores.add(t_Valor_madera, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        t_Consultar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        t_Consultar.setForeground(new java.awt.Color(0, 0, 0));
        t_Consultar.setText("Consultar Valor");
        Valores.add(t_Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, -1));
        Valores.add(Fecha_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));
        Valores.add(Fecha_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        Cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadActionPerformed(evt);
            }
        });
        Valores.add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 90, 30));
        Valores.add(Valor_mad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 90, 30));

        Consultar_valor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagescon_valor.png"))); // NOI18N
        Consultar_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar_valorActionPerformed(evt);
            }
        });
        Valores.add(Consultar_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 160, 150));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo apli3negro2.png"))); // NOI18N
        Valores.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        SAlir2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SAlir2.setForeground(new java.awt.Color(0, 0, 0));
        SAlir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir2.png"))); // NOI18N
        SAlir2.setText("Salir");
        SAlir2.setContentAreaFilled(false);
        SAlir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAlir2ActionPerformed(evt);
            }
        });
        Valores.add(SAlir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        Regresa1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Regresa1.setForeground(new java.awt.Color(0, 0, 0));
        Regresa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresa_negro.png"))); // NOI18N
        Regresa1.setText("Regresar");
        Regresa1.setContentAreaFilled(false);
        Regresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresa1ActionPerformed(evt);
            }
        });
        Valores.add(Regresa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/todas_proy.jpg"))); // NOI18N
        Valores.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
        Valores.add(Mostrar_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 330, -1, 10));

        getContentPane().add(Valores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Regresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar1ActionPerformed
        presentacion.setVisible(true);
        Datos.setVisible(false);
    }//GEN-LAST:event_Regresar1ActionPerformed

    private void B_ingres_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ingres_datosActionPerformed
        Datos.setVisible(true);
        presentacion.setVisible(false);
    }//GEN-LAST:event_B_ingres_datosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Date a = Fecha.getDatoFecha();
        int b= Integer.parseInt(Cant_arb.getText());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        //Calendar cal = getCalendar(a);
        for(int i=0; i<b; i++){
           fechas.enqueue(a);           
        }        
        mensaje_resultado.showMessageDialog(null,b+" Datos Ingresados con la fecha "+ sdf.format(a));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SAlirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAlirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SAlirActionPerformed

    private void Consultar_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar_valorActionPerformed
        int cant=Integer.parseInt(Cantidad.getText());
        int val_mad=Integer.parseInt(Valor_mad.getText());
        Mostrar_res.showMessageDialog(null,"el valor para los datos seleccionados es "+ calcular_valor(cant,val_mad));
    }//GEN-LAST:event_Consultar_valorActionPerformed

    private void SAlir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAlir2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SAlir2ActionPerformed

    private void Regresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresa1ActionPerformed
        Valores.setVisible(false);
        presentacion.setVisible(true);
    }//GEN-LAST:event_Regresa1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        presentacion.setVisible(false);
        Valores.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SAlir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAlir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SAlir1ActionPerformed

    private void CantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        //String usuarios= usuario.getText();
        //String Contrasenas= contraseña.getText();
        //System.out.println(usuarios+Contrasenas);
        //if (usuarios=="salomon" && Contrasenas =="1234"){
            Lanzar_aplix.setVisible(true);
            aaranque.setVisible(false);            
        //}
        //else{
         //   Error_contra.showMessageDialog(null," El usuario o contraseña estan mal ");
       // }
    }//GEN-LAST:event_entrarActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        presentacion.setVisible(true);
        Lanzar_aplix.setVisible(false);
        
    }//GEN-LAST:event_boton1ActionPerformed

    private void RegresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresaActionPerformed
        presentacion.setVisible(false);
        Lanzar_aplix.setVisible(true);
        
    }//GEN-LAST:event_RegresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplicacion_completa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplicacion_completa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplicacion_completa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplicacion_completa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplicacion_completa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_ingres_datos;
    private javax.swing.JTextField Cant_arb;
    private javax.swing.JTextField Cantidad;
    private javax.swing.JButton Consultar_valor;
    private javax.swing.JPanel Datos;
    private javax.swing.JOptionPane Error_contra;
    private rojeru_san.componentes.RSDateChooser Fecha;
    private rojeru_san.componentes.RSDateChooser Fecha_fin;
    private rojeru_san.componentes.RSDateChooser Fecha_ini;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo3;
    private javax.swing.JPanel Lanzar_aplix;
    private javax.swing.JLabel Logo;
    private javax.swing.JOptionPane Mostrar_res;
    private javax.swing.JButton Regresa;
    private javax.swing.JButton Regresa1;
    private javax.swing.JButton Regresar1;
    private javax.swing.JButton SAlir;
    private javax.swing.JButton SAlir1;
    private javax.swing.JButton SAlir2;
    private javax.swing.JLabel T_consultar_valores;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField Valor_mad;
    private javax.swing.JPanel Valores;
    private javax.swing.JPanel aaranque;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JTextField contraseña;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo_inicial;
    private javax.swing.JLabel fondo_lanza;
    private javax.swing.JLabel imagen_1;
    private javax.swing.JLabel imagen_2;
    private javax.swing.JLabel imgen_4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo2;
    private javax.swing.JOptionPane mensaje_resultado;
    private javax.swing.JPanel presentacion;
    private javax.swing.JLabel t_Cantidad;
    private javax.swing.JLabel t_Consultar;
    private javax.swing.JLabel t_Valor_madera;
    private javax.swing.JLabel t_fecha_fin;
    private javax.swing.JLabel t_fecha_in;
    private javax.swing.JLabel t_ingresar_cantidad;
    private javax.swing.JLabel t_ingresar_fecha;
    private javax.swing.JLabel text_ingresar_datos;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
